name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - '26.3'
          - '27.1'
          - '28.2'
          - '29.3'
          - 'snapshot'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Install mu4e
        run: |
          sudo sed -i '/^deb/P;s/^deb/deb-src/' /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install git meson emacs
          sudo apt-get build-dep maildir-utils
          cd /usr/local/src
          sudo git clone https://github.com/djcb/mu.git
          cd mu
          sudo ./autogen.sh && sudo make && sudo make install

      - name: Compile
        run: make compile USE_SYSTEM_MU4E=1
