name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          # - '26.3' # It might be supported, but CI build fails.
          - '27.1'
          - '28.2'
          - '29.4'
          - '30.1'
          - 'snapshot'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Install mu4e
        run: |
          emacs=`which emacs`

          # Ubuntu<24
          test -e /etc/apt/sources.list && \
            sudo sed -i '/^deb/P;s/^deb/deb-src/' /etc/apt/sources.list
          # Ubuntu>=24
          sudo sed -i 's/^Types: deb/Types: deb deb-src/' /etc/apt/sources.list.d/*

          sudo apt-get update
          sudo apt-get install git meson emacs
          sudo apt-get build-dep maildir-utils
          cd /usr/local/src
          sudo git clone https://github.com/djcb/mu.git
          cd mu
          sudo ./autogen.sh -Demacs=$emacs && sudo make && sudo make install

      - name: Compile
        run: make compile USE_SYSTEM_MU4E=1

      - name: Lint
        run: make lint
